version: '3'
services:
  db1:
    image: postgres
    volumes:
      - db1_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_db1: app_development
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    networks:
      - backend

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db1
    environment:
      DATABASE_URL: postgres://postgres:password@db1:5432/app_development
      RAILS_ENV: development
      RAILS_MASTER_KEY: c05bb6dc94e26b347f3209a1ac1a7192
    networks:
      - backend

volumes:
  db1_data: {}

networks:
  backend:
